const fs = require('node:fs'), path = require('node:path');
const root = __dirname, out = path.join(root, 'powerbi');
function write(file, value) {const full = path.join(out, file); fs.mkdirSync(path.dirname(full), {recursive: true}); fs.writeFileSync(full, typeof value === 'string' || Buffer.isBuffer(value) ? value : JSON.stringify(value, null, 2));}
const roles = ['SubID', 'Site', 'PlannedSubmission', 'ActualSubmission', 'BusinessUnit', 'SubStatus', 'ROStatus', 'AppStatus', 'DispatchRequired', 'PlannedDispatch', 'ActualDispatch'];
const names = {SubID: 'Submission ID', Site: 'Site (legal manufacturer)', PlannedSubmission: 'Planned submission date', ActualSubmission: 'Actual submission date', BusinessUnit: 'Business unit (optional)', SubStatus: 'Submission state (optional)', ROStatus: 'RO state (optional)', AppStatus: 'Application state (optional)', DispatchRequired: 'Dispatch required (optional)', PlannedDispatch: 'Planned dispatch date (optional)', ActualDispatch: 'Actual dispatch date (optional)'};
write('package.json', {name: 'site-submission-outlook', version: '1.3.0', private: true, scripts: {typecheck: 'tsc --noEmit', package: 'pbiviz package'}, dependencies: {'powerbi-visuals-api': '5.11.0'}, devDependencies: {'powerbi-visuals-tools': '7.2.1', typescript: '5.9.3', '@playwright/test': '1.55.1', esbuild: '0.25.10'}});
write('pbiviz.json', {visual: {name: 'siteSubmissionOutlook', displayName: 'Site Submission Outlook', guid: 'siteSubmissionOutlook8D94A67E43154927AC034613F8289C02', visualClassName: 'Visual', version: '1.3.0.0', description: 'Current and next month planned submissions, internal dispatch versus authority-submission delays, and lifecycle state filters across six sites.', supportUrl: 'https://github.com/DangerMitch2000/regulatory-reporting-and-submission-tracker/issues', gitHubUrl: 'https://github.com/DangerMitch2000/regulatory-reporting-and-submission-tracker'}, apiVersion: '5.11.0', author: {name: 'Dualta Mitchell', email: 'dualtamitchell@gmail.com'}, assets: {icon: 'assets/icon.png'}, externalJS: null, style: 'style/visual.less', capabilities: 'capabilities.json', dependencies: null, stringResources: []});
write('capabilities.json', {privileges: [], dataRoles: roles.map(name => ({name, displayName: names[name], kind: 'Grouping', description: ['PlannedSubmission','ActualSubmission','PlannedDispatch','ActualDispatch'].includes(name) ? 'Use a raw date column, not a date hierarchy. Do not summarize.' : 'Map the source column; no renaming is necessary.'})), dataViewMappings: [{conditions: [Object.fromEntries(roles.map(name => [name, {max: 1}]))], table: {rows: {select: roles.map(role => ({for: {in: role}})), dataReductionAlgorithm: {window: {count: 30000}}}}}], objects: {preferences: {displayName: 'Preferences', properties: {state: {displayName: 'Saved selections', type: {text: true}}}}}, supportsHighlight: false, supportsKeyboardFocus: true, supportsEmptyDataView: true, sorting: {default: {}}});
write('tsconfig.json', {compilerOptions: {allowJs: true, checkJs: false, allowSyntheticDefaultImports: true, esModuleInterop: true, target: 'es2022', module: 'esnext', moduleResolution: 'node', sourceMap: true, outDir: './.tmp/build', declaration: false, skipLibCheck: true, lib: ['es2022', 'dom']}, files: ['src/visual.ts']});
for (const file of ['submissions.logic.mjs', 'submissions.ui.mjs', 'visual.ts']) write('src/' + file, fs.readFileSync(path.join(root, file)));
write('style/visual.less', fs.readFileSync(path.join(root, 'submissions.css')));
write('README.md', fs.readFileSync(path.join(root, 'README.md')));
const zlib = require('node:zlib');
function crc(buffer) {let c = 0xffffffff; for (const byte of buffer) {c ^= byte; for (let j = 0; j < 8; j++) c = (c >>> 1) ^ ((c & 1) ? 0xedb88320 : 0);} return (c ^ 0xffffffff) >>> 0;}
function chunk(type, buffer) {const t = Buffer.from(type), length = Buffer.alloc(4), checksum = Buffer.alloc(4); length.writeUInt32BE(buffer.length); checksum.writeUInt32BE(crc(Buffer.concat([t, buffer]))); return Buffer.concat([length, t, buffer, checksum]);}
const header = Buffer.alloc(13); header.writeUInt32BE(20); header.writeUInt32BE(20, 4); header[8] = 8; header[9] = 6;
const pixels = Buffer.alloc(1620);
for (let y = 0; y < 20; y++) for (let x = 0; x < 20; x++) {let rgba = [255, 255, 255, 255]; if (x > 2 && x < 8 && y > 7 && y < 18 || x > 10 && x < 16 && y > 3 && y < 18) rgba = y > 12 ? [23, 110, 176, 255] : [97, 205, 180, 255]; pixels.set(rgba, y * 81 + 1 + x * 4);}
write('assets/icon.png', Buffer.concat([Buffer.from([137,80,78,71,13,10,26,10]), chunk('IHDR', header), chunk('IDAT', zlib.deflateSync(pixels)), chunk('IEND', Buffer.alloc(0))]));
console.log('Generated Site Submission Outlook 1.3.0 with four required data roles, optional business unit, lifecycle states and three dispatch fields.');
