(async()=>{
 'use strict';
 const $=id=>document.getElementById(id), chart=$('chart'),status=$('filter-status'),detail=$('selected-details');
 const fields={site:'Manufacturer',product:'Product',country:'Country',type:'SubmissionType',businessUnit:'BusinessUnit'},selected=Object.fromEntries(Object.keys(fields).map(k=>[k,new Set()]));
 const norm=x=>x==null?'':String(x).trim(),el=(tag,text,cls)=>{const e=document.createElement(tag);if(text!==undefined)e.textContent=text;if(cls)e.className=cls;return e;};
 let view,rows,queue=Promise.resolve(),detailQuery='',detailPage=0,selectedKey='',timer;const filterBoxes=[];let predictionAnalysis;let predictionFieldsMissing=[];const predictions=window.regulatoryPredictions;
 const quality=window.regulatoryQuality; const qualityUI=window.regulatoryQualityUI; const exportWorklist=window.regulatoryExportWorklist; let qualityMappedFields=null,qualityAnalysis,qualityPanel;
 const submissionPeriod=window.regulatorySubmissionPeriod;let submissionDates=new Map(),unidentifiedDates=new Map();
 const run=fn=>queue=queue.then(fn).catch(error=>{status.textContent='Could not update the chart: '+error.message;console.error(error);});
 const date=x=>x==null||!Number.isFinite(x)?'Not recorded':new Date(x).toISOString().slice(0,10);
 const duration=x=>x==null?'Not recorded / withheld':Math.round(x)+' days';
 document.body.dataset.theme='dark';
 try{
  const [spec,data]=window.__demoBundle?[window.__demoBundle.spec,window.__demoBundle.rows]:await Promise.all(['timeline.json','sample.json'].map(async url=>{const r=await fetch(url+'?v=1.9.1');if(!r.ok)throw Error('Unable to load '+url);return r.json();}));rows=data;preparePredictions();prepareQuality();qualityPanel=qualityUI.mount($('quality-view'),{exportWorklist});
  const showQuality=enabled=>{$('quality-view').hidden=!enabled;$('timeline-view').hidden=enabled;status.hidden=enabled;$('timeline-tab').setAttribute('aria-pressed',String(!enabled));$('quality-tab').setAttribute('aria-pressed',String(enabled));$('tooltip').hidden=true;};
  $('quality-tab').onclick=()=>showQuality(true);$('timeline-tab').onclick=()=>showQuality(false);
  // These are genuine Vega HTML input bindings, also included in the Deneb deliverable.
  view=new vega.View(vega.parse(spec),{renderer:'svg',hover:true}).initialize(chart,$('bindings')).tooltip((h,event,item,value)=>{
   const tip=$('tooltip');if(value==null){tip.hidden=true;return;}tip.replaceChildren();for(const [k,v]of Object.entries(typeof value==='object'?value:{Details:value})){tip.append(el('strong',k+': '),el('span',String(v)),el('br'));}tip.hidden=false;tip.style.left=Math.max(6,Math.min(event.clientX+12,innerWidth-330))+'px';tip.style.top=Math.max(6,Math.min(event.clientY+12,innerHeight-160))+'px';
  });
  const stateLegend=$('state-legend');
  const states=[['Active / Planned','#6d9eff'],['In progress / Ready','#43c6ec'],['Sent / Distributed','#bd9aff'],['HA received','#42cbbb'],['Completed','#65d18c'],['Health Authority Approved','#37d67a'],['Hold / Deferred','#e8b65f'],['Rejected','#f27b82'],['Inactive / Other','#99a4b5']];
  for(const [label,colour]of states){const wrap=el('label'),cb=el('input'),sw=el('span',undefined,'state-swatch');cb.type='checkbox';cb.checked=true;cb.value=colour;sw.dataset.stateColour=colour;sw.style.background=colour;wrap.append(cb,sw,el('span',label));stateLegend.append(wrap);cb.onchange=()=>run(async()=>{view.signal('stateColours',[...stateLegend.querySelectorAll('input:checked')].map(x=>x.value));await view.runAsync();updateStatus();});}
  $('theme-select').onchange=()=>{const mode=$('theme-select').value==='light'?'light':'dark';run(async()=>{document.body.dataset.theme=mode;view.signal('themeMode',mode);await view.runAsync();const colours=view.signal('themeStateColors');for(const sw of stateLegend.querySelectorAll('.state-swatch'))sw.style.background=colours[sw.dataset.stateColour]||sw.dataset.stateColour;const badge=$('detail-body').querySelector('.state-badge'),row=view.data('selectedRow')[0];if(badge&&row)badge.style.color=colours[row.StateColor]||row.StateColor;});};
  const labelFor=kind=>kind==='site'?'Site (LM)':kind==='businessUnit'?'Business Unit':kind[0].toUpperCase()+kind.slice(1);
  for(const [kind,field]of Object.entries(fields)){
   const box=el('details',undefined,'filter'),summary=el('summary',labelFor(kind)+' · All'),panel=el('div',undefined,'panel'),search=el('input');box.dataset.kind=kind;search.type='search';search.placeholder=kind==='product'?'Type at least 2 characters…':'Search '+labelFor(kind);search.setAttribute('aria-label','Search '+labelFor(kind)+' options');
   const choices=el('div',undefined,'options'),chosen=el('div',undefined,'chosen-options'),help=el('p',undefined,'filter-help'),actions=el('div',undefined,'filter-actions'),all=el('button','Select shown'),clear=el('button','Clear');actions.append(all,clear);panel.append(search,help,chosen,actions,choices);box.append(summary,panel);$('filters').prepend(box);
   let values=[],inputTimer;
   const candidates=()=>rows.filter(r=>kind!=='product'||['businessUnit','site'].every(k=>!selected[k].size||selected[k].has(norm(r[fields[k]]))));
   const refreshValues=()=>{values=[...new Set(candidates().map(r=>norm(r[field])))].sort();};
   const matches=()=>kind==='product'&&search.value.trim().length<2?[]:values.filter(x=>(x||'(Missing)').toLowerCase().includes(search.value.trim().toLowerCase()));
   const shown=()=>matches().slice(0,50);
   const option=(value,target)=>{const label=el('label',undefined,'option'),cb=el('input');cb.type='checkbox';cb.checked=selected[kind].has(value);label.append(cb,el('span',value||'(Missing)'));target.append(label);cb.onchange=()=>{cb.checked?selected[kind].add(value):selected[kind].delete(value);update();draw();};};
   const draw=()=>{choices.replaceChildren();chosen.replaceChildren();if(!box.open)return;const found=matches(),visible=found.slice(0,50),picked=[...selected[kind]];help.textContent=kind==='product'&&search.value.trim().length<2?'Type at least 2 characters to find products.':('Showing '+visible.length+' of '+found.length+' matches. Refine your search for more.');if(picked.length){chosen.append(el('strong',picked.length+' selected'));picked.filter(v=>(v||'(Missing)').toLowerCase().includes(search.value.trim().toLowerCase())).slice(0,50).forEach(v=>option(v,chosen));if(picked.length>50)chosen.append(el('p','First 50 selected shown; search to find others.'));}visible.filter(v=>!selected[kind].has(v)).forEach(v=>option(v,choices));all.disabled=!visible.length;};
   const update=()=>{summary.textContent=labelFor(kind)+' · '+(selected[kind].size?selected[kind].size+' selected':'All');if(kind==='businessUnit'||kind==='site')filterBoxes.filter(b=>b.kind==='product').forEach(b=>b.refresh());filter();};
   search.oninput=()=>{clearTimeout(inputTimer);inputTimer=setTimeout(draw,140)};all.onclick=()=>{shown().forEach(x=>selected[kind].add(x));draw();update();};clear.onclick=()=>{selected[kind].clear();draw();update();};
   box.ontoggle=()=>{if(box.open){for(const other of $('filters').querySelectorAll('details'))if(other!==box)other.open=false;draw();}else{choices.replaceChildren();chosen.replaceChildren();}};
   box.reset=()=>{selected[kind].clear();search.value='';summary.textContent=labelFor(kind)+' · All';refreshValues();draw();};
   filterBoxes.push({kind,refresh(){refreshValues();draw()},dispose(){clearTimeout(inputTimer)}});refreshValues();
  }
  const dateBox=$('submission-date-filter');dateBox.reset=()=>{$('submission-period').value='all';$('submission-from').value='';$('submission-to').value='';updateDateControl();};
  dateBox.ontoggle=()=>{if(dateBox.open)for(const other of $('filters').querySelectorAll('details'))if(other!==dateBox)other.open=false;};
  $('submission-period').onchange=()=>{updateDateControl();filter();};for(const id of ['submission-from','submission-to'])$(id).onchange=()=>{updateDateControl();filter();};
  $('clear-submission-period').onclick=()=>{dateBox.reset();filter();};
  $('reset-filters').onclick=()=>{qualityPanel.reset();for(const cb of stateLegend.querySelectorAll('input'))cb.checked=true;run(()=>view.signal('stateColours',states.map(s=>s[1])).runAsync());for(const box of $('filters').querySelectorAll('details'))box.reset();filterBoxes.forEach(f=>f.refresh());run(async()=>{view.signal('query','');await view.runAsync();});filter();};
  const resize=new ResizeObserver(entries=>{const {width,height}=entries[0].contentRect;run(()=>view.signal('denebContainer',{width:Math.max(720,width),height:Math.max(480,height)}).runAsync());});resize.observe(chart);
  chart.addEventListener('pointerdown',e=>{if(!e.target.closest('input,select'))chart.focus({preventScroll:true});});
  for(const name of ['selectedKey','query','mode','compareLevel','pinsOnly','pinClick','showRegistrationEnd','sortBy','axisMode'])view.addSignalListener(name,()=>{clearTimeout(timer);timer=setTimeout(()=>{updateStatus();renderDetails();updateControls();},0);});
  // The separate browser details list has full native caret, paste and selection behaviour.
  $('list-search').oninput=e=>{detailQuery=e.target.value;detailPage=0;renderDetails();};
  $('list-prev').onclick=()=>{detailPage=Math.max(0,detailPage-1);renderDetails();};$('list-next').onclick=()=>{detailPage++;renderDetails();};
  $('copy-details').onclick=async()=>{const row=view.data('selectedRow')[0];if(!row)return;const text=$('detail-body').innerText+'\n\nFull products\n'+row.ProductInfo.members.map(x=>x.label).join('\n')+'\n\nFull countries\n'+row.CountryInfo.members.map(x=>x.label).join('\n')+'\n\nFull legal manufacturers\n'+row.ManufacturerInfo.members.map(x=>x.label).join('\n');await copy(text,$('copy-status'));};
  $('copy-id').onclick=async()=>{const row=view.data('selectedRow')[0];if(row)await copy(row.level===2?row.SubID:row.level===1?row.ROID:row.AppID,$('copy-status'));};
  $('clear-pins').onclick=()=>run(async()=>{view.change('pinned',vega.changeset().remove(()=>true));await view.runAsync();updateStatus();});
  detail.ontoggle=()=>document.body.classList.toggle('details-expanded',detail.open);
  await filter();$('bindings').append($('clear-pins'));updateControls();
  // POWERBI_MOUNT_READY
  function preparePredictions(){const opts={now:new Date(),...(qualityMappedFields?{mappedFields:qualityMappedFields}:{})};submissionDates=predictions.resolveSubmissionDates(rows,opts);unidentifiedDates=new Map(rows.filter(row=>!norm(row.SubID)).map(row=>[row,predictions.resolveSubmissionDates([{...row,SubID:'_unidentified_'}],opts).get('_unidentified_')]));predictionAnalysis=predictionFieldsMissing.length?{bySubID:new Map()}:predictions.analyze(rows,opts);refreshDateChoices();}
  function chosenPeriod(){return submissionPeriod.compile({mode:$('submission-period').value,from:$('submission-from').value,to:$('submission-to').value});}
  function updateDateControl(){const p=chosenPeriod();$('submission-custom').hidden=$('submission-period').value!=='custom';$('submission-date-summary').textContent='Submission date · '+p.label;$('submission-date-error').textContent=p.error;$('submission-date-error').hidden=!p.error;for(const id of ['submission-from','submission-to'])$(id).setAttribute('aria-invalid',String(!!p.error));return p;}
  function refreshDateChoices(){const picker=$('submission-period'),previous=picker.value||'all',options=[['all','All dates'],...submissionPeriod.years([...submissionDates.values(),...unidentifiedDates.values()]).map(year=>['year:'+year,String(year)]),['custom','Custom range'],['undated','No usable date']];if(previous.startsWith('year:')&&!options.some(([v])=>v===previous))options.splice(1,0,[previous,previous.slice(5)+' (no matching dates)']);picker.replaceChildren(...options.map(([value,label])=>{const o=el('option',label);o.value=value;return o;}));picker.value=previous;updateDateControl();}
  function prepareQuality(){qualityAnalysis=quality.analyze(rows,{now:new Date(),...(qualityMappedFields?{mappedFields:qualityMappedFields}:{})});}
  function enriched(row){const p=predictionAnalysis.bySubID.get(norm(row.SubID));return {...row,PredictionDate:p?.predictedDate??null,PredictionLow:p?.rangeStart??null,PredictionHigh:p?.rangeEnd??null,PredictionN:p?.sampleCount??0,PredictionMedian:p?.medianDays??null,PredictionCountry:p?.country??'',PredictionStatus:p?.status??'unavailable',PredictionAnchorDate:p?.anchorDate??null,PredictionAnchorField:p?.anchorField??'',PredictionAnchorLabel:p?.anchorLabel??'',PredictionFromPlan:p?.forecastFromPlan??false};}
  function filter(){return run(async()=>{const period=updateDateControl(),matching=rows.filter(row=>Object.entries(fields).every(([kind,field])=>!selected[kind].size||selected[kind].has(norm(row[field])))&&submissionPeriod.matches(norm(row.SubID)?submissionDates.get(norm(row.SubID)):unidentifiedDates.get(row),period));view.change('dataset',vega.changeset().remove(()=>true).insert(matching.map(enriched)));await view.runAsync();qualityPanel.update(qualityAnalysis,matching);detailPage=0;updateStatus();renderDetails();});}
  function updateStatus(){const roCount=view.data('roTotals')[0]?.count??0;status.textContent=view.data('sub').length+' submissions · '+roCount+(roCount===1?' RO · ':' ROs · ')+view.data('apps').length+' applications · '+view.data('pinned').length+' pinned';}
  function updateControls(){for(const binding of $('bindings').children){const name=binding.querySelector('input,select')?.name;if(['compareLevel','axisMode','sortBy','pinsOnly'].includes(name))binding.hidden=view.signal('mode')!=='Compare';if(name==='axisMode')binding.hidden=view.signal('mode')!=='Compare'||view.signal('compareLevel')!==2;if(name==='detailQuery')binding.hidden=true;}$('comparison-help').hidden=view.signal('mode')!=='Compare';$('clear-pins').hidden=view.signal('mode')!=='Compare';}
  function renderDetails(){
   const row=view.data('selectedRow')[0],body=$('detail-body'),lists=$('member-lists');body.replaceChildren();lists.replaceChildren();
   if(selectedKey!==view.signal('selectedKey')){selectedKey=view.signal('selectedKey');detailQuery='';$('list-search').value='';detailPage=0;}
   if(!row){$('detail-title').textContent=selectedKey?'Details · selection outside current filters':'Details · select a row or membership count';body.append(el('p','Select a submission, or a parent subtitle or membership count.'));$('detail-tools').hidden=true;return;}
   $('detail-tools').hidden=false;const id=row.level===2?row.SubID:row.level===1?row.ROID:row.AppID;
   $('detail-title').textContent='Details · '+id+' · '+row.State;
   const heading=el('h2',id),badge=el('span',row.State,'state-badge');badge.style.color=view.signal('themeStateColors')[row.StateColor]||row.StateColor;heading.append(badge);body.append(heading);
   if(row.level===2)body.append(el('p',row.SubmissionType,'type-label'));
   const relations=el('dl',undefined,'relationships');for(const [label,value]of [['Application',row.AppID],['Regulatory objective',row.ROID],['Legal manufacturer',row.ManufacturerInfo.detail],['Countries',row.CountryInfo.detail]]){relations.append(el('dt',label),el('dd',value||'Not recorded'));}body.append(relations);
   if(row.level===2){
    renderPrediction(body,predictionAnalysis.bySubID.get(norm(row.SubID)));
    const more=el('details',undefined,'record-history');more.append(el('summary','All milestone dates and processing history'));body.append(more);
    const table=el('table'),head=el('tr');for(const t of ['Milestone','Original','Latest','Actual'])head.append(el('th',t));table.append(head);
    for(const stage of ['Dispatch','Submission','Approval']){const tr=el('tr');tr.append(el('th',stage));for(const prefix of ['Original','Latest','Actual']){const field=prefix+stage;tr.append(el('td',row[field+'Bad']>0||row[field+'Min']!==row[field+'Max']?'Withheld — see data issues':date(row[field])));}table.append(tr);}more.append(table);
    const endText=row.RegistrationEndBad>0?'Withheld — invalid date':row.RegistrationEndMin!==row.RegistrationEndMax?'Withheld — conflicting dates':(row.RegistrationEnd==null?'No registration end date':date(row.RegistrationEnd));const reg=el('p','Registration start: '+date(row.RegistrationStart)+' · Registration end: '+endText);more.append(reg);
    const metrics=el('table'),tr=el('tr');for(const t of ['Completed duration','Value'])tr.append(el('th',t));metrics.append(tr);for(const [label,value]of [['Dispatch → submission',duration(row.DispatchDays)],['Submission → approval',duration(row.ApprovalDays)],['Current stage waiting time',row.OpenAge?row.OpenAge.replace(/^Open (approval|submission) (\d+)d$/,(_,stage,days)=>'Awaiting '+stage+' · '+days+' days'):'No open stage / not recorded']]){const tr=el('tr');tr.append(el('th',label),el('td',value));metrics.append(tr);}more.append(metrics);
    const variance=el('table'),vh=el('tr');for(const t of ['Actual variance (days)','vs Original','vs Latest'])vh.append(el('th',t));variance.append(vh);for(const stage of ['Dispatch','Submission','Approval']){const tr=el('tr');tr.append(el('th',stage));for(const baseline of ['Original','Latest']){const val=row[stage+baseline+'Variance'];tr.append(el('td',val==null?'Not recorded':(val>0?'+':'')+Math.round(val)));}variance.append(tr);}more.append(variance,el('p','Positive variance means later than the plan. Open age is not a completed duration.','muted'));
   }else body.append(el('p',(row.level===0?row.ROCount+' distinct ROs · ':'')+row.n+' distinct submissions'),el('p','Child submission states: '+row.Breakdown.label));
   const issues=[];if(row.level===2){for(const key of ['OriginalDispatch','LatestDispatch','ActualDispatch','OriginalSubmission','LatestSubmission','ActualSubmission','OriginalApproval','LatestApproval','ActualApproval','RegistrationStart','RegistrationEnd']){if(row[key+'Bad']>0)issues.push(key+(key==='RegistrationEnd'?': invalid date, withheld from timeline':': invalid input, withheld'));else if(row[key+'Min']!==row[key+'Max'])issues.push(key+': conflicting dates, withheld');else if(row[key+'Valid']>0&&row[key+'Valid']<row.sourceRows)issues.push(key+': some membership rows are blank');}if(row.Reversed)issues.push('Reversed actual processing dates: duration withheld');}if(row.State==='Conflicting values')issues.push('Conflicting own-state values; neutral colour');body.append(el('h3','Data issues'),el('p',issues.length?issues.join(' · '):row.level<2?row.issues+' withheld milestone fields across children':'No conflicting or invalid milestone values detected.'));
   const groups=[['Products',row.ProductInfo],['Countries',row.CountryInfo],['Legal manufacturers',row.ManufacturerInfo]],q=detailQuery.toLowerCase();let max=1;
   for(const [label,info]of groups){const found=info.members.map(m=>m.label).filter(x=>x.toLowerCase().includes(q));max=Math.max(max,Math.ceil(found.length/12));}
   detailPage=Math.min(detailPage,max-1);
   for(const [label,info]of groups){const section=el('section'),found=info.members.map(m=>m.label).filter(x=>x.toLowerCase().includes(q));section.append(el('h3',label+' · '+found.length+' matching'));const ul=el('ul');for(const item of found.slice(detailPage*12,detailPage*12+12))ul.append(el('li',item));if(!ul.children.length)ul.append(el('li','No values on this page'));section.append(ul);lists.append(section);}
   $('list-page').textContent=(detailPage+1)+' / '+max;$('list-prev').disabled=detailPage===0;$('list-next').disabled=detailPage>=max-1;
  }
  function renderPrediction(body,p){
   const grid=el('div',undefined,'prediction-grid'),record=el('section',undefined,'prediction-card'),estimate=el('section',undefined,'prediction-card estimate'),history=el('section',undefined,'prediction-card');
   record.append(el('h3','Approval record'));const row=view.data('selectedRow')[0],fields=[['Actual submission','ActualSubmission'],['Latest planned submission','LatestSubmission'],['Original planned submission','OriginalSubmission'],['Original approval','OriginalApproval'],['Latest approval','LatestApproval'],['Actual approval','ActualApproval']];
   const dl=el('dl');fields.forEach(([k,f])=>dl.append(el('dt',k),el('dd',qualityMappedFields&&!qualityMappedFields.includes(f)?'Not mapped':row[f+'Bad']>0||row[f+'Min']!==row[f+'Max']?'Withheld — invalid or conflicting':date(row[f]))));record.append(dl);
   const benchmark=p?.status==='benchmark'||p?.selfExcluded;
   estimate.append(el('h3',benchmark?'Historical approval benchmark':p?.forecastFromPlan?'Forecast based on planned submission':'Approval estimate'));
   if(p?.status==='estimated'||p?.status==='benchmark'){estimate.append(el('strong',date(p.predictedDate),'prediction-date'),el('p','Historical middle 50%: '+date(p.rangeStart)+' – '+date(p.rangeEnd)),el('p','Based on '+(p.anchorLabel||'Actual submission')+': '+date(p.anchorDate)),el('p','Median: '+Math.round(p.medianDays)+' days'),el('p',benchmark?'Retrospective comparison using current history, not a forecast made before approval.':p?.forecastFromPlan?'Assumes submission occurs on its planned date. Recorded approval plans stay alongside this forecast.':'Independent historical estimate; recorded approval plans stay alongside it.','prediction-note'));if(p.overdue&&!benchmark)estimate.append(el('p','Historical estimate has passed; this is not a revised future forecast.','prediction-warning'));}
   else estimate.append(el('strong',benchmark?'Benchmark unavailable':'Estimate unavailable'),el('p',predictionFieldsMissing.length?'Map these prediction fields: '+predictionFieldsMissing.join(', '):p?.reason||'Insufficient reliable history or source dates.'));
   history.append(el('h3','Supporting history'),el('p',(p?.country||'Country unavailable')+' · Country-based median'),el('p',(p?.sampleCount??0)+' qualifying submissions'),el('p',(p?.excludedCount??0)+' excluded from completed country history'),el('p','Both actual dates: January 2020 to today'));
   if(!p?.selfExcluded)history.append(el('p','At least 10 qualifying records required.','muted'));
   if(p?.selfExcluded)history.append(el('p','This submission is excluded from its own benchmark. At least 10 other qualifying submissions are required.','prediction-note'));
   if(p?.outlierCount)history.append(el('p',p.outlierCount+' unusually long durations retained; review recommended.','prediction-warning'));
   if(p?.exclusions){const checks=el('details');checks.append(el('summary','Exclusion reasons'));const list=el('ul');p.exclusions.forEach(({label,count})=>{if(count)list.append(el('li',label+': '+count))});list.append(el('li','Reasons can overlap; pending records are excluded because approval is not recorded.'));checks.append(list);history.append(checks);}
   grid.append(record,estimate,history);body.append(grid,el('p','History uses all records delivered to this visual, before its local filters. Power BI report filters and data limits can reduce that history. Historical ranges are not guaranteed forecasts; valid-looking source dates may still be wrong.','muted'));
  }
  async function copy(text,target){try{await navigator.clipboard.writeText(text);target.textContent='Copied';}catch{target.textContent='Clipboard unavailable here. Select the text and use Copy.';}}
 }catch(error){status.textContent='Could not load the demo: '+error.message;console.error(error);}
})();
