(function(root,factory){const api=factory(typeof module==='object'&&module.exports?require('./events.js'):root.regulatoryEvents,typeof module==='object'&&module.exports?require('./states.js'):root.regulatoryStates);if(typeof module==='object'&&module.exports)module.exports=api;if(root)root.regulatoryChanges=api;})(typeof globalThis==='object'?globalThis:this,function(events,states){
 'use strict';
 const text=v=>v==null?'':String(v).trim(),norm=v=>text(v).toLowerCase(),unique=a=>[...new Set(a)],natural=(a,b)=>a.localeCompare(b,undefined,{numeric:true,sensitivity:'base'}),key=(...a)=>JSON.stringify(a);
 function linked(r){return !!(text(r.ChangeID)&&text(r.EventName)&&norm(r.EventQMS)&&norm(r.EventQMS)===norm(r.ChangeQMS));}
 function duration(value){const m=text(value).match(/^(\d+(?:\.\d+)?)\s*(?:[-–—]|to)?\s*(\d+(?:\.\d+)?)?\s*(days?|weeks?|months?)$/i);if(!m)return null;const n=+m[1],end=m[2]?+m[2]:n,f=/month/i.test(m[3])?30:/week/i.test(m[3])?7:1;return n>0&&end>=n&&end*f<=36500?{low:n*f,high:end*f}:null;}
 function survey(records){const groups=new Map();for(const r of records){if(!linked(r)||!text(r.AssessmentCountry)||!text(r.AssessmentTimeline))continue;const k=key(text(r.ChangeID),norm(r.AssessmentCountry));if(!groups.has(k))groups.set(k,[]);groups.get(k).push(r);}
 return [...groups.values()].map(rs=>{const r=rs[0],values=unique(rs.map(x=>text(x.AssessmentTimeline))),parsed=values.map(duration),same=parsed.every(p=>p&&p.low===parsed[0]?.low&&p.high===parsed[0]?.high);let reason=same?'':'Invalid, reversed or conflicting survey durations — range withheld.';const countries=unique(rs.map(x=>norm(x.Country)).filter(Boolean));if(!countries.includes(norm(r.AssessmentCountry)))reason='Assessment country does not match this submission.';let anchor=null,anchorLabel='';for(const [field,label]of [['ActualDispatch','Actual dispatch'],['LatestDispatch','Latest dispatch plan'],['OriginalDispatch','Original dispatch plan']]){const d=events.dateField(rs,field);if(d.label==='Not recorded')continue;anchor=d.value;anchorLabel=label;if(anchor===null)reason=label+': '+d.label;break;}if(anchor===null&&!reason)reason='A valid dispatch date or plan is needed.';return {change:text(r.ChangeID),country:text(r.AssessmentCountry),duration:values.join(' / '),anchorLabel,reason,start:reason?null:anchor+parsed[0].low*86400000,end:reason?null:anchor+parsed[0].high*86400000,source:'Change Impact Assessment Tool — SharePoint'};});}
 function related(row,source){return source.filter(r=>(row.level===-2&&row.changeOther ? !linked(r) : !row.ChangeID||text(r.ChangeID)===row.ChangeID)&&(!row.EventName|| (row.unlinked ? !text(r.EventName) : text(r.EventName)===row.EventName))&&(row.level<0||text(r.AppID)===row.AppID)&&(row.level<1||text(r.ROID)===row.ROID)&&(row.level<2||text(r.SubID)===row.SubID));}
 function build(source,sub,apps,ros){const groups=new Map();for(const r of source){const id=linked(r)?text(r.ChangeID):'';if(!groups.has(id))groups.set(id,[]);groups.get(id).push(r);}const names=[...groups.keys()].filter(Boolean).sort(natural),result=[];
 for(const [id,input]of groups){const child=events.build(input,sub,apps,ros);if(!child.length)continue;const member=new Set(child.filter(r=>r.level===2).map(r=>key(r.AppID,r.ROID,r.SubID))),rs=input.filter(r=>member.has(key(text(r.AppID),text(r.ROID),text(r.SubID))));const ck=key('change',id),common={ChangeID:id,changeKey:ck,changeRank:names.indexOf(id),changeOther:id?0:1};for(const row of child){row.key=key(ck,row.key);for(const f of ['appKey','roKey','eventKey'])if(row[f])row[f]=key(ck,row[f]);Object.assign(row,common);}const stateValues=unique(rs.map(r=>text(r.ChangeStatus)).filter(Boolean)),state=id?(stateValues.length>1?'Conflicting values':stateValues[0]||'Not recorded'):'Not applicable',planned=events.dateField(rs,'ChangePlannedImplementation'),p={...child[0],...common,level:-2,key:ck,eventKey:null,EventName:'',AppID:'',ROID:'',State:state,StateColor:states.colour(state),start:id?planned.value:null,end:id?planned.value:null,ChangePlanLabel:planned.label,EventCount:unique(rs.map(r=>text(r.EventName)).filter(Boolean)).length,AppCount:unique(rs.map(r=>text(r.AppID)).filter(Boolean)).length,ROCount:unique(rs.map(r=>text(r.ROID)).filter(Boolean)).length,n:unique(rs.map(r=>text(r.SubID)).filter(Boolean)).length};for(const f of ['Manufacturer','Country','Product']){const members=unique(rs.map(r=>text(r[f])).filter(Boolean)).sort().map(label=>({label}));p[f+'Info']={members,count:members.length,detail:members.map(x=>x.label).join(' · '),label:members.length===1?members[0].label:members.length+' values'};}p.SiteLabel=p.ManufacturerInfo.label;p.ProductLabel=p.ProductInfo.label;p.ProductCountLabel=p.ProductInfo.count+' products';p.CountryCountLabel=p.CountryInfo.count+' countries';p.shortTip={Record:id||'Other regulatory events',State:state};result.push(p,...child);}
 return result.map(r=>Object.fromEntries(Object.entries(r)));}
 function order(rows,descending){const ranks=f=>{const names=unique(rows.map(r=>text(r[f])).filter(Boolean)).sort(natural);return new Map(names.map((n,i)=>[n,descending?names.length-i:i+1]));},a=ranks('AppID'),r=ranks('ROID'),s=ranks('SubID');return rows.map(row=>({...Object.fromEntries(Object.entries(row)),rankApp:row.level<0?0:a.get(row.AppID)||0,rankRO:row.level<1?0:r.get(row.ROID)||0,rankSub:row.level<2?0:s.get(row.SubID)||0}));}
 return {linked,duration,survey,related,build,order};
});
