const fs=require('fs');
const sample=`const year=new Date().getFullYear(),rows=Array.from({length:96},(_,i)=>({SubID:'DEMO-'+i,OriginalDispatch:year+'-'+String(i%12+1).padStart(2,'0')+'-12',ActualDispatch:i%3===0?year+'-'+String(i%12+1).padStart(2,'0')+'-14':null,ActualSubmission:i%4===1?year+'-06-01':null,Site:['North','Central','South','East','West','Coastal',null][Math.floor(i/7)%7],BusinessUnit:['ID','CMI','CSP','TOX'][Math.floor(i/3)%4],DispatchRequired:[true,false,null][i%3],Project:['IVDR','Rebranding',null,'UDI; IVDR','UDI'][i%5]}));rows.push({SubID:'UNDATED',ActualApproval:year+'-01-01',Site:'Northern site',BusinessUnit:'ID',Project:null},{SubID:'UNDATED-NOT-REQUIRED',DispatchRequired:false,ActualApproval:year+'-02-02',Site:'North',BusinessUnit:'ID',Project:'IVDR'});`;
const helper=fs.readFileSync('dispatch-required.js','utf8'),strip=p=>fs.readFileSync(p,'utf8').replace(/^import .*\r?\n/gm,'').replace(/^export \{.*\};\r?\n/gm,'').replaceAll('export ',''),logic='const roadmapModule=(()=>{const dispatchModule=globalThis.regulatoryDispatchRequired;'+strip('ivdr-roadmap.logic.js')+';return {summarize,viewingDay,roles,categories}})();',comparison='const comparisonModule=(()=>{const {summarize,viewingDay,roles:roadmapRoles,categories}=roadmapModule;const dispatchModule=globalThis.regulatoryDispatchRequired;'+strip('ivdr-comparison.logic.js')+';return {compare,viewingDay,categories,dispatchRequiredOptions}})();',ui='const {compare,viewingDay,categories,dispatchRequiredOptions}=comparisonModule;'+strip('ivdr-comparison.ui.js'),css=fs.readFileSync('ivdr-comparison.css','utf8');
const app=`${sample}const root=document.querySelector('#host');let state={},expanded=new Set();function draw(){render(root,rows,{synthetic:true,state,expanded,onChange:patch=>{state={...state,...patch};draw()},onExpansion:key=>{expanded.has(key)?expanded.delete(key):expanded.add(key);draw()}})}draw();`;
fs.writeFileSync('ivdr-preview.html','<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>IVDR Registration Overview 1.2.0 — fictional demo</title><style>'+css+'body{margin:20px;background:#edf2f7;font:15px Segoe UI}#host{width:min(1400px,100%);margin:auto;height:900px}</style><div id="host"></div><script>'+helper+'\n'+logic+'\n'+comparison+'\n'+ui+'\n'+app+'</script></html>');
fs.mkdirSync('ivdr-comparison/verify',{recursive:true});
fs.writeFileSync('ivdr-comparison/verify/harness.ts',`import {Visual} from '../src/visual';import {roles} from '../src/ivdr-comparison.logic';${sample}
const host={eventService:{renderingStarted(){},renderingFinished(){document.body.dataset.ready='true'},renderingFailed(o,e){throw Error(e)}},fetchMoreData(){return false}};
const visual=new Visual({element:document.getElementById('host'),host} as any);const send=(data=rows,project=true,dispatch=true)=>visual.update({type:2,viewport:{width:1320,height:1000},dataViews:[{metadata:{},table:{columns:roles.filter(k=>(project||k!=='Project')&&(dispatch||k!=='DispatchRequired')).map(role=>({roles:{[role]:true}})),rows:data.map(r=>roles.filter(k=>(project||k!=='Project')&&(dispatch||k!=='DispatchRequired')).map(k=>r[k]))}}]} as any);send();
document.getElementById('resize').onclick=()=>visual.update({type:4,viewport:{width:650,height:1000}} as any);document.getElementById('reset').onclick=()=>send();document.getElementById('empty').onclick=()=>send([]);document.getElementById('unmapped').onclick=()=>send(rows,false);
document.getElementById('dispatch-unmapped').onclick=()=>send(rows,true,false);
`);
fs.writeFileSync('ivdr-comparison/verify/index.html','<!doctype html><meta charset="utf-8"><link rel="stylesheet" href="harness.css"><div id="host"></div><button id="resize">Narrow</button><button id="reset">Reset</button><button id="empty">Empty</button><button id="unmapped">Unmapped</button><button id="dispatch-unmapped">Dispatch unmapped</button><script src="harness.js"></script>');
