(function(root,factory){const api=factory();if(typeof module==='object'&&module.exports)module.exports=api;if(root)root.regulatoryStates=api;})(typeof globalThis==='object'?globalThis:this,function(){
 'use strict';
 const catalogs={ChangeStatus:['Completed','In Progress','Not recorded'],AppStatus:['Active','Inactive'],ROStatus:['Archived','Conditionally Approved','Health Authority Approved','In Progress','On Hold By Health Authority','On Hold By Mah','Planned','Rejected','Withdrawn'],SubStatus:['Completed','Deferred','Distributed','HA Received','In Progress','Inactive','Planned','Ready For Submission','Rejected','Sent To Health Authority','Withdrawn'],EventState:['Cancelled State','Closed State','In Progress State','In Regulatory Assessment State','Inactive State','Planned State','Regulatory Assessment Complete State']};
 const labels={ChangeStatus:'Change status',AppStatus:'Application state',ROStatus:'RO state',SubStatus:'Submission state',EventState:'Event state'};
 const colours={'active':'#4d91e8','inactive':'#939aa5','archived':'#8294ab','conditionally approved':'#a3bd45','health authority approved':'#27ae78','in progress':'#f09342','on hold by health authority':'#d9b44a','on hold by mah':'#b88960','planned':'#a17be8','rejected':'#e35b64','withdrawn':'#bd718d','completed':'#70b85c','deferred':'#e5a17e','distributed':'#e177b3','ha received':'#39b8aa','ready for submission':'#52bfe0','sent to health authority':'#808be5','cancelled state':'#e27c70','closed state':'#9aa66a','in progress state':'#db772b','in regulatory assessment state':'#c16ccb','inactive state':'#a79a8c','planned state':'#b49bdb','regulatory assessment complete state':'#65a994','not recorded':'#abb4c2','conflicting values':'#e06ded'};
 const text=v=>v==null?'':String(v).trim(),normalize=v=>text(v).toLowerCase()||'not recorded';
 function colour(v){return colours[normalize(v)]||'#abb4c2';}
 const rgb=h=>[1,3,5].map(i=>parseInt(h.slice(i,i+2),16)),hex=a=>'#'+a.map(n=>Math.round(n).toString(16).padStart(2,'0')).join('');
 function luminance(h){const a=rgb(h).map(n=>{n/=255;return n<=.04045?n/12.92:((n+.055)/1.055)**2.4});return a[0]*.2126+a[1]*.7152+a[2]*.0722;}
 function readable(h,background,light){let a=rgb(h);for(let i=0;i<70;i++){const l=luminance(hex(a)),b=luminance(background);if((Math.max(l,b)+.05)/(Math.min(l,b)+.05)>=4.6)return hex(a);a=a.map(n=>light?n*.95:n+(255-n)*.05);}return hex(a);}
 const dark=Object.fromEntries(Object.values(colours).map(c=>[c,readable(c,'#344460',false)])),light=Object.fromEntries(Object.values(colours).map(c=>[c,readable(c,'#dceaff',true)]));
 function entity(row,field){return field==='ChangeStatus'?JSON.stringify([text(row.ChangeID)]):field==='AppStatus'?JSON.stringify([text(row.AppID)]):field==='ROStatus'?JSON.stringify([text(row.AppID),text(row.ROID)]):field==='SubStatus'?JSON.stringify([text(row.SubID)]):JSON.stringify([text(row.EventName)]);}
 function analyze(rows){const result={};for(const field of Object.keys(catalogs)){const groups=new Map();for(const r of rows){const k=entity(r,field);if(!groups.has(k))groups.set(k,new Set());if(text(r[field]))groups.get(k).add(normalize(r[field]));}result[field]=new Map([...groups].map(([k,v])=>[k,v.size>1?'conflicting values':v.values().next().value||'not recorded']));}return result;}
 function matches(row,analysis,excluded){return Object.keys(catalogs).every(f=>!excluded[f].has(analysis[f].get(entity(row,f))||'not recorded'));}
 return {catalogs,labels,colours,colour,dark,light,normalize,analyze,matches};
});
