const assert=require('node:assert/strict'),path=require('node:path');
module.exports=async(page,{outputDir})=>{
 await page.goto('http://127.0.0.1:8771/index.html');await page.locator('#host #filter-status').filter({hasText:'60 submissions'}).waitFor();
 const rev=await page.evaluate(()=>window.__qualityRevision);await page.evaluate(()=>{const r={...window.__dispatchRows[0],AppID:'A',ROID:'R',SubID:'S1',AppStatus:'Active',ROStatus:'Planned',SubStatus:'Planned',EventName:'E2',EventState:'In Progress State',Manufacturer:'Example site'};window.__dispatchSend([r,{...r,EventName:'E10'},{...r,ROID:'R2',SubID:'S2',SubStatus:'Completed'},{...r,AppID:'B',ROID:'R3',SubID:'S3',AppStatus:'Inactive',ROStatus:'In Progress',SubStatus:'Distributed',EventName:null,EventState:null}]);});await page.waitForFunction(n=>window.__qualityRevision>n,rev);
 const count=page.locator('#host #filter-status');assert.match(await count.innerText(),/^0 change IDs · 2 events · 2 applications · 3 ROs · 3 submissions/);assert.match(await page.locator('#host .intro').innerText(),/Event → Application → RO → Submission/);
 const sub=page.locator('#host .state-filter[data-field=SubStatus]');await sub.locator('summary').click();assert.equal(await sub.getByLabel('In Progress',{exact:true}).count(),1);assert.equal(await sub.getByLabel('Ready For Submission',{exact:true}).count(),1);assert.equal(await sub.getByLabel('Distributed',{exact:true}).count(),1);await sub.getByLabel('Planned',{exact:true}).uncheck();await count.filter({hasText:'2 submissions'}).waitFor();assert.match(await count.innerText(),/^0 change IDs · 1 events · 2 applications · 2 ROs · 2 submissions/);await sub.locator('summary').click();
 await page.locator('#host #reset-filters').click();await count.filter({hasText:'3 submissions'}).waitFor();await page.locator('#host select[name=mode]').selectOption('Compare');
 const fill=await page.locator('#host .subLabel text').evaluateAll(es=>es.map(e=>e.getAttribute('fill')));assert.equal(new Set(fill).size,3);
 await sub.locator('summary').click();await page.mouse.move(5,5);await page.locator('#host').screenshot({path:path.join(outputDir,'states-dark.png')});await sub.locator('summary').click();await page.locator('#host #theme-select').selectOption('light');await page.locator('#host').screenshot({path:path.join(outputDir,'states-light.png')});
 const point=await page.evaluate(()=>{const v=window.__themeVisual.app.view,b=document.querySelector('#host #chart svg').getBoundingClientRect();return {x:b.x+v.signal('left')+200,y:b.y+v.signal('top')+45};});const range=()=>page.evaluate(()=>{const v=window.__themeVisual.app.view;return [v.signal('xlo'),v.signal('xhi')]});
 const before=await range();await page.mouse.move(point.x,point.y);await page.keyboard.down('Control');await page.mouse.wheel(0,100);await page.keyboard.up('Control');await page.waitForTimeout(120);const after=await range();assert.ok(after[0]>before[0]);assert.ok((after[0]-before[0])/(before[1]-before[0])<.025,'Fine pan uses small fraction of current zoom');
 await page.mouse.move(point.x,point.y);await page.mouse.down();await page.mouse.move(point.x+30,point.y,{steps:5});await page.mouse.up();await page.waitForTimeout(100);const dragged=await range();assert.ok(dragged[0]<after[0]);assert.ok(Math.abs((dragged[1]-dragged[0])-(after[1]-after[0]))<2,'Dragging preserves zoom');
 await page.keyboard.down('Shift');await page.mouse.wheel(0,-100);await page.keyboard.up('Shift');await page.waitForTimeout(100);const zoomed=await range();assert.ok(zoomed[1]-zoomed[0]<dragged[1]-dragged[0]);assert.ok((zoomed[1]-zoomed[0])/(dragged[1]-dragged[0])>.9,'Zoom steps are gentle');
 const fraction=await page.evaluate(x=>{const v=window.__themeVisual.app.view,b=document.querySelector('#host #chart svg').getBoundingClientRect();return (x-b.x-v.signal('left'))/(v.signal('width')-v.signal('left'));},point.x+30);assert.ok(Math.abs((dragged[0]+fraction*(dragged[1]-dragged[0]))-(zoomed[0]+fraction*(zoomed[1]-zoomed[0])))<(dragged[1]-dragged[0])/500,'Zoom preserves date under pointer within one screen pixel');
 // Use enough rows to expose accidental vertical scrolling during modified wheel gestures.
 await page.evaluate(()=>window.__dispatchSend(window.__dispatchRows));
 await page.waitForTimeout(250);
 await page.evaluate(async()=>{const v=window.__themeVisual.app.view;v.signal('rowRequest',{pos:8});await v.runAsync();});
 const scrollState=()=>page.evaluate(()=>({row:window.__themeVisual.app.view.signal('scrollTop'),pageX:window.scrollX,pageY:window.scrollY}));
 const fixed=await scrollState();
 const wheelPoint=await page.evaluate(()=>{const v=window.__themeVisual.app.view,b=document.querySelector('#host #chart svg').getBoundingClientRect();return {x:b.x+v.signal('left')+100,y:b.y+v.signal('top')+40};});
 await page.mouse.move(wheelPoint.x,wheelPoint.y);
 for(const key of ['Shift','Control']){await page.keyboard.down(key);await page.mouse.wheel(0,100);await page.keyboard.up(key);await page.waitForTimeout(120);assert.deepEqual(await scrollState(),fixed,key+' wheel must not scroll rows or page');}
 await page.mouse.wheel(0,100);await page.waitForTimeout(120);assert.ok((await scrollState()).row>fixed.row,'Unmodified wheel still scrolls rows');
 console.log('PASS: separate state dropdowns, independent Planned filter, ordered distinct counts, state-coloured names, themes, fine Ctrl+wheel, background drag and pointer-centred Shift zoom.');
};
